### ISSUE TITLE
Add support for Responsive Design variants

### ISSUE THREAD

**Issue by javergar** [phthhieu/re-tailwind#8]
First of all great job; we are using re-tailwind for a prototype implementation that is planned to go into production.

At the moment we are supporting responsive design variants by using bs-css `addUnsafeClass` but it would be great to have this out of the box and strongly typed.

`let navBarBody  = TW.( [Display(Block)              
] |> make) |> addUnsafeClass("lg:hidden");`

Let me know if I can help on this.

Thanks Again
Alberto

**Comment by phthhieu** [comment]
@javergar Let me update a bit to support this. Thanks

**Comment by phthhieu** [comment]
@javergar Published the update @ 0.0.4

Enjoy ReasonML & Tailwind
